# -*- coding: utf-8 -*-
"""FeaturePlots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ojjppN_8x385ZYGTcQ5SV4z4vuYxWgf0
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime

df = pd.read_csv("..\\finalDatasets.csv")

df

ct = datetime.datetime.now()

"""##  Placement Status plot"""

plt.subplot(231)
ax=sns.countplot(x="Placement_status", data=df, facecolor=(0, 0, 0, 0),
                 linewidth=5,edgecolor=sns.color_palette("hot", 3))
fig = plt.gcf()
fig.set_size_inches(10,10)
ax.set_xticklabels(ax.get_xticklabels(),fontsize=12)
plt.title("Visualizing Placement Status:- " + str(ct))
fig = ax.get_figure()
fig.savefig(r"src\\main\\resources\\static\\css\\placementStatus.png")
plt.clf()

"""## Important Feature Plot"""

X=df.drop(['Placement_status','CandidateName'],axis=1)
y=df.Placement_status

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.8,random_state=1)

from sklearn.ensemble import RandomForestClassifier
rt=RandomForestClassifier(n_estimators=100)
rt.fit(X_train,y_train)
y_pred=rt.predict(X_test)
from sklearn import metrics
print("Placement Probability : ",round(metrics.accuracy_score(y_test, y_pred) * 100) ,"%")
print("\n")

df.columns

feature_cols = [ 'Languages', 'BigDataAnalysis',
       'CodingAndProgramming', 'DataScience', 'DevOps', 'CloudComputing',
       'OperatingSystem', 'WebDevelopement', 'DBMS', 'AppDevelopment',
       'Security', 'Others', 'CGPA']

feature_imp = pd.Series(rt.feature_importances_,index=feature_cols).sort_values(ascending=False)
# Creating a bar plot
bx = sns.barplot(x=feature_imp, y=feature_imp.index)
# Add labels to your graph
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')
plt.title("Visualizing Important Features:- " + str(ct))
fig = bx.get_figure()
fig.savefig(r"src\\main\\resources\\static\\css\\featureImp.png" )

